# Generated by Django 5.2.7 on 2025-10-28 03:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodSensor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('water_level', models.FloatField(default=0.0)),
                ('is_emergency', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'flood_sensors',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RFIDAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rfid_uid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('adult', 'Adult'), ('non-adult', 'Non-Adult'), ('deceased', 'Deceased')], default='adult', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('emergency', 'Emergency')], default='public', max_length=20)),
                ('balance', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rfid_accounts',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('topup', 'Top-Up')], max_length=10)),
                ('gate_id', models.CharField(default='gate1', max_length=20)),
                ('old_balance', models.FloatField(default=0.0)),
                ('new_balance', models.FloatField(default=0.0)),
                ('amount_changed', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('rfid_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='toll_system.rfidaccount')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
