# Generated by Django 5.2.7 on 2025-10-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toll_system', '0002_alter_floodsensor_id_alter_rfidaccount_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_changed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='old_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
